# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 17:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='negative_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['TBC'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='neutral_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['TBC'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='positive_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['TBC'], size=None),
            preserve_default=False,
        ),
    ]
